// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Order struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Status    sql.NullString `json:"status"`
	Total     sql.NullString `json:"total"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type OrderItem struct {
	ID        int32  `json:"id"`
	OrderID   int32  `json:"order_id"`
	ProductID int32  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	UnitPrice string `json:"unit_price"`
}

type Product struct {
	ID          int32          `json:"id"`
	Sku         string         `json:"sku"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Available   sql.NullBool   `json:"available"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type ProductCategory struct {
	ProductID  int32 `json:"product_id"`
	CategoryID int32 `json:"category_id"`
}

type User struct {
	ID           int32          `json:"id"`
	Email        string         `json:"email"`
	FullName     sql.NullString `json:"full_name"`
	PasswordHash string         `json:"password_hash"`
	CreatedAt    time.Time      `json:"created_at"`
}
