// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package db

import (
	"context"
)

const addOrderItem = `-- name: AddOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, unit_price
`

type AddOrderItemParams struct {
	OrderID   int32  `json:"order_id"`
	ProductID int32  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	UnitPrice string `json:"unit_price"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, addOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}

const calculateOrderTotal = `-- name: CalculateOrderTotal :one
SELECT COALESCE(SUM(quantity * unit_price), 0)::numeric
FROM order_items
WHERE order_id = $1
`

func (q *Queries) CalculateOrderTotal(ctx context.Context, orderID int32) (string, error) {
	row := q.db.QueryRowContext(ctx, calculateOrderTotal, orderID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT oi.id, oi.order_id, oi.product_id, oi.quantity, oi.unit_price, p.name
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = $1
`

type ListOrderItemsRow struct {
	ID        int32  `json:"id"`
	OrderID   int32  `json:"order_id"`
	ProductID int32  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	UnitPrice string `json:"unit_price"`
	Name      string `json:"name"`
}

func (q *Queries) ListOrderItems(ctx context.Context, orderID int32) ([]ListOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsRow
	for rows.Next() {
		var i ListOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
