// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error)
	CalculateOrderTotal(ctx context.Context, orderID int32) (string, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	GetProductsByCategory(ctx context.Context, id int32) ([]Product, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListAvailableProducts(ctx context.Context, arg ListAvailableProductsParams) ([]Product, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListOrderItems(ctx context.Context, orderID int32) ([]ListOrderItemsRow, error)
	ListOrdersByUser(ctx context.Context, userID int32) ([]Order, error)
	SearchProductsByName(ctx context.Context, dollar_1 sql.NullString) ([]Product, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
